version: '3.7'
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - adminer
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      inception:
        ipv4_address: 172.20.0.4
    env_file:
      - .env
    restart: always
  
  wordpress:
    build:
      context: requirements/wordpress/
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_USER: ${WP_USER}
        WP_USER_PASSWORD: ${WP_USER_PASSWORD}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
    container_name: wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      inception:
        ipv4_address: 172.20.0.3
    restart: always

  mariadb:
    build:
      context: requirements/mariadb/
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      inception:
        ipv4_address: 172.20.0.10
    restart : always

  adminer:
    build:
      context: requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      inception:
        ipv4_address: 172.20.0.7

    restart: always

  redis:
    build:
      context: requirements/bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      inception:
        ipv4_address: 172.20.0.5
    depends_on:
      - nginx
      - wordpress
    restart: always

  ftp:
    build:
      context: requirements/bonus/ftp
      args:
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
    container_name: ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      inception:
        ipv4_address: 172.20.0.6
    volumes:
      - wordpress_volume:/home/${WP_ADMIN_USER}
    depends_on:
      - wordpress
      - nginx
    env_file:
      - .env
    restart: always

  dns:
    build:
      context: requirements/bonus/dns
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: dns
    ports:
      - "53:53"
      - "53:53/udp"
    env_file:
      - .env
    networks:
      inception:
        ipv4_address: 172.20.0.8
    restart: always

    

volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /Users/beadam/Desktop/inception/inception/srcs/Data/wordpress
      type: none
      o: bind
  mariadb_volume:
    name: mariadb_volume
    driver_opts:
      device: /Users/beadam/Desktop/inception/inception/srcs/Data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
