version: '3.7'
services:
  nginx:
    build: requirements/ngnix/
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:  
      - wordpress_volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: requirements/mariadb/
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    restart : on-failure


volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /Users/beadam/Desktop/inception/inception/srcs/Data/wordpress
      type: none
      o: bind
  mariadb_volume:
    name: mariadb_volume
    driver_opts:
      device: /Users/beadam/Desktop/inception/inception/srcs/Data/mariadb
      type: volume
      o: bind
  # maria_test:
  #   name: maria_test
  #   driver: local
  #   # driver_opts:
  #   #   device: /Users/beadam/Desktop/inception/inception/srcs/Data/maria_test
  #   #   type: volume
  #   #   o: bind

networks:
  inception:
    name: inception
    driver: bridge